// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("TodoApp");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "app"
                }, React.createElement("div", {
                      className: "title"
                    }, "What to do"), React.createElement("div", {
                      className: "items"
                    }, "Nothing"));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
